[project]
name = "sunshine-app-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "glob2>=0.7",
    "pillow>=11.3.0",
    "psutil>=7.0.0",
    "requests>=2.32.4",
    "vdf>=3.4",
]
